### ISSUE TITLE
Old icons on "detail" toot

### ISSUE THREAD

**Issue by afk-mcz** [merveilles/The-Town#12]
When you click a toot and it opens on a new column, it shows the default mastodon icons.
![image](https://user-images.githubusercontent.com/1025751/50313160-1fed3b80-0470-11e9-9129-921900058b2a.png)

**Comment by neauoire** [comment]
Fixed

**Comment by offalynne** [comment]
still seeing this, is the live site not the latest? `public-layout` and `.detailed-status__meta` buttons require restyling to match `.status__action-bar` buttons.

**Comment by neauoire** [comment]
Right, the tiny ones.

**Comment by eelfroth** [comment]
fixed this in #23

**Comment by offalynne** [comment]
almost ! one more ;-(

![image](https://user-images.githubusercontent.com/16347732/50385280-2f070000-06a1-11e9-8dea-b109c7c5ad74.png)
